### ISSUE TITLE
dpath.util.merge raises TypeError with list of dicts

### ISSUE THREAD

**Issue by v1k45** [dpath-maintainers/dpath-python#131]
In earlier version (1.4.2) merging a list of dict was possible:

```python
>>> y = [{'x': 'y', 'foo': 'bar'}]
>>> x = [{'x': 'x'}]
>>> dpath.merge(x, y, flags=dpath.MERGE_REPLACE)
>>> x
[{'x': 'y', 'foo': 'bar'}]
>>>
```

Now it is not:

```python
>>> import dpath.util
>>>
>>> y = [{'x': 'y', 'foo': 'bar'}]
>>> x = [{'x': 'x'}]
>>>
>>> dpath.util.merge(x, y, flags=dpath.util.MERGE_REPLACE)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/dpath/util.py", line 351, in merge
    merger(dst, filtered_src)
  File "/usr/local/lib/python3.8/site-packages/dpath/util.py", line 291, in merger
    if len(key) == 0 and not options.ALLOW_EMPTY_STRING_KEYS:
TypeError: object of type 'int' has no len()
>>>
```

Is this intended behavior or a bug?

**Comment by moomoohk** [comment]
Hi,
After further consideration I've come to the conclusion this isn't intended usage.

**Comment by moomoohk** [comment]
Quite welcome
