### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by nakvic** [dpath-maintainers/dpath-python#142]
Python 2.7.16: import dpath.util raises exception:

>>> import dpath.util
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/dpath/util.py", line 1, in <module>
    from collections.abc import MutableMapping
ImportError: No module named abc

**Comment by moomoohk** [comment]
Hi,
Python 2 will not be supported moving forward
