### ISSUE TITLE
TypeError: unhashable type: 'SymmetricInt' on searching through a list of nested dictionaries. (since 2.1.2)

### ISSUE THREAD

**Issue by ArnoldJudas** [dpath-maintainers/dpath-python#178]
### The following works well on python 3.11 with dpath 2.1.1

packages:
```
[tool.poetry.dependencies]
python = "^3.11"
dpath = "2.1.1"
```

main.py
```
import dpath
t2 = [{'info': {'label': 'a',
                'placeholder': 'A',
                'value': 'some text'}
       },
      {'info': {'label': 'b',
                'placeholder': 'B',
                'value': ''}},
      {'info': {'label': 'c',
                'placeholder': 'C',
                'value': ''}}]

if __name__ == '__main__':
    print(dpath.search(t2, '**/placeholder', afilter=lambda x: 'C' == x))
```

result
```
{2: {'info': {'placeholder': 'C'}}}
```

### The same script on python 3.11 with dpath 2.1.2 and onward

result
```
Traceback (most recent call last):
  File "/home/user/.cache/pypoetry/virtualenvs/dpath-test-l92W8Ykb-py3.11/lib/python3.11/site-packages/dpath/segments.py", line 347, in set
    current[segment]
    ~~~~~~~^^^^^^^^^
TypeError: unhashable type: 'SymmetricInt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/Projects/dpath_test/dpath_test.py", line 25, in <module>
    print(dpath.search(t2, '**/placeholder', afilter=lambda x: 'C' == x))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.cache/pypoetry/virtualenvs/dpath-test-l92W8Ykb-py3.11/lib/python3.11/site-packages/dpath/__init__.py", line 245, in search
    return segments.fold(obj, f, {})
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.cache/pypoetry/virtualenvs/dpath-test-l92W8Ykb-py3.11/lib/python3.11/site-packages/dpath/segments.py", line 387, in fold
    if f(obj, pair, acc) is False:
       ^^^^^^^^^^^^^^^^^
  File "/home/user/.cache/pypoetry/virtualenvs/dpath-test-l92W8Ykb-py3.11/lib/python3.11/site-packages/dpath/__init__.py", line 243, in f
    segments.set(result, path, found, hints=segments.types(obj, path))
  File "/home/user/.cache/pypoetry/virtualenvs/dpath-test-l92W8Ykb-py3.11/lib/python3.11/site-packages/dpath/segments.py", line 350, in set
    creator(current, segments, i, hints)
  File "/home/user/.cache/pypoetry/virtualenvs/dpath-test-l92W8Ykb-py3.11/lib/python3.11/site-packages/dpath/segments.py", line 302, in _default_creator
    current[segment] = hints[i][1]()
    ~~~~~~~^^^^^^^^^
TypeError: unhashable type: 'SymmetricInt'

Process finished with exit code 1
```

**Comment by moomoohk** [comment]
Apologies, the `SymmetricInt` type indeed does not implement the `__hash__` method. It's a simple fix however I'll only be able to implement it tomorrow.

**Comment by moomoohk** [comment]
Hi @ArnoldJudas, after further investigation I've realized you're passing a `list` of `dicts`.
In the past (in the context of `merge` not `search`), I've defined this usage as unsupported (https://github.com/dpath-maintainers/dpath-python/issues/162 https://github.com/dpath-maintainers/dpath-python/issues/131).
Implementing the `__hash__` method on `SymmetricInt` is probably necessary, however I'll have to further consider how `search` should behave in this case. Regular `int`s should be returned by `search` and not `SymmetricInt`s it in any event
Suggestions are welcome.

**Comment by moomoohk** [comment]
Before closing this issue due to inactivity I would like to suggest a workaround for you that should work with newer versions of dpath:


```python
import dpath
t2 = [{'info': {'label': 'a',
                'placeholder': 'A',
                'value': 'some text'}
       },
      {'info': {'label': 'b',
                'placeholder': 'B',
                'value': ''}},
      {'info': {'label': 'c',
                'placeholder': 'C',
                'value': ''}}]


if __name__ == '__main__':
    for i, d in enumerate(t2):
        if result := dpath.search(d, "**/placeholder", afilter=lambda x: "C" == x):
            print(i, result)
```

Hope this helps.

Please feel free to reopen with any new information or suggestions.
